### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by mostar** [matthewniemerg/steem-autovote-bot#1]
Hi,

I followed the example, tried to run the script. The output error is not clear to me:

```
{'otheruser': {'myuser': {'random_wait': 0, 'frequency': 1}}}
Traceback (most recent call last):
  File "autoupvote-bot.py", line 306, in <module>
    main()
  File "autoupvote-bot.py", line 295, in main
    my_max_random_wait = monitor[a][b]['min_random_wait']
KeyError: 'min_random_wait'
```

Other try

```
{'otheruser': {'myuser': {'random_wait': 2, 'min_random_wait': 1, 'max_random_wait': 10, 'frequency': 1}}}
myuser  is monitoring otheruser with a random wait between 1  and 10 seconds with a probability of 1
Traceback (most recent call last):
  File "autoupvote-bot.py", line 306, in <module>
    main()
  File "autoupvote-bot.py", line 301, in main
    monitor_loop(settings, wallet)
  File "autoupvote-bot.py", line 200, in monitor_loop
    last_block = cur_info["result"]["last_irreversible_block_num"]
KeyError: 'result'
```

I'm successfully connected to sync running node
Any advice will be appreciated

**Comment by matthewniemerg** [comment]
Sorry.  I didn't update the documentation.

If you look in the example file that I provide, there is a new value called 'min_random_wait'. This is required.  'max_random_wait' is optional.  But, other than that, it's the same syntax.  Updating docs shortly.

**Comment by mostar** [comment]
Thank you, I added min_random_wait
Now it failing on

`
{'user1': {'user2': {'min_random_wait': 1, 'max_random_wait': 10, 'frequency': 1}}}
user2 is monitoring user1 with a random wait between 1  and 10 seconds with a probability of 1

Traceback (most recent call last):
  File "autoupvote-bot.py", line 306, in <module>
    main()
  File "autoupvote-bot.py", line 301, in main
    monitor_loop(settings, wallet)
  File "autoupvote-bot.py", line 200, in monitor_loop
    last_block = cur_info["result"]["last_irreversible_block_num"]
KeyError: 'result'
`
